### ISSUE TITLE
New dataframe Units

### ISSUE THREAD

**Issue by open-source-modelling** [open-source-modelling/Open_Source_Economic_Model#67]
Until now, market value is used for each equity. This is simple to manage, however it does not scale and it limits the options for further development. 

The proposal is to create a ledger of "units" of each asset. So that the market value of each position is calculated as market value * units held.

This allows to bring a separation between the movement of price of an asset and the trading activities of a each portfolio.

**Comment by GregorFabjan** [comment]
Units added to input test file and in main loop
