### ISSUE TITLE
ImportData.py has undocumented functions

### ISSUE THREAD

**Issue by open-source-modelling** [open-source-modelling/Open_Source_Economic_Model#81]

**Comment by GregorFabjan** [comment]
get_EquityShare() and get_Cash() now have documentation. 

Remaining:
 - get_configuration
 - import_SWEiopa
 - get_corporate_bonds
 - get_Liability
 - get_settings

**Comment by GregorFabjan** [comment]
get_Liability() and get_settings() now have documentation.

Remaining:

get_configuration()
import_SWEiopa()
get_corporate_bonds()

**Comment by open-source-modelling** [comment]
get_configuration() and import_SWEiopa() now have documentation.

Remaining:
-get_configuration()

**Comment by open-source-modelling** [comment]
get_configuration() documentation in the last pull from @GregorFabjan
